/** 福岡 8/13–18 行程資料 · 博多站住宿 */
const TRIP = {
  meta: {
    title: "福岡 6 天 5 夜",
    dates: "2026/8/13 – 8/18",
    base: "博多站",
    baseLat: 33.5897,
    baseLng: 130.4207,
    flightOut: { airline: "CX588", date: "8/13", from: "HKG 11:00", to: "FUK 15:30" },
    flightBack: { airline: "CX529", date: "8/18", from: "FUK 17:40", to: "HKG 20:25" },
  },

  bookings: [
    { id: "b-fireworks", status: "skip", label: "關門海峽煙火協賛席", day: 1, note: "❌ 不去 · 抵達日趕不及 · 票作廢／確認退票規則" },
    { id: "b-yanagawa", status: "must", label: "柳川遊船 15:40", day: 2, url: "https://www.yanagawa-kanko.jp/", note: "夏季 10:10–15:40 停航" },
    { id: "b-teamlab", status: "must", label: "teamLab Forest 時段票", day: 5, url: "https://www.teamlab.art/zh-hant/e/forest/", note: "熱門時段常售罄" },
    { id: "b-pass", status: "should", label: "太宰府・柳川觀光套票", day: 2, url: "https://www.nishitetsu.jp/kippu/tc/dazaifu-yanagawa/", note: "數位版 ¥3,620" },
    { id: "b-unagi", status: "should", label: "元祖本吉屋 / 若松屋", day: 2, note: "週末午餐建議電話預約" },
    { id: "b-yufuin-mori", status: "should", label: "由布院之森 指定席", day: 4, url: "https://www.jrkyushu.co.jp/yufuin_nomori/", note: "8/16 週日熱門 · 博多 07:33 或 08:00 班次 · 可改 Sonic" },
    { id: "b-motsu", status: "should", label: "元祖牛腸鍋 樂天地", day: 3, note: "8/15 週六晚餐 · 電話或官網" },
  ],

  transportGuide: [
    { dest: "福岡機場", how: "地鐵空港線", time: "5 分", cost: "¥260" },
    { dest: "天神", how: "地鐵（2 站）", time: "3 分", cost: "¥200" },
    { dest: "太宰府", how: "地鐵→西鐵（天神出發）", time: "50 分", cost: "套票" },
    { dest: "柳川", how: "西鐵特急（天神出發）", time: "55 分", cost: "套票" },
    { dest: "由布院", how: "JR 久大本線（ゆふいんの森／ソニック）", time: "約 2hr", cost: "¥4,410 起" },
    { dest: "小倉 / 門司", how: "JR 新幹線", time: "20 分", cost: "¥2,150" },
    { dest: "大濠公園", how: "地鐵空港線", time: "10 分", cost: "¥260" },
    { dest: "teamLab / LaLaport", how: "巴士（百道浜）", time: "25 分", cost: "¥230" },
    { dest: "下關唐戶", how: "門司港→關門聯絡船", time: "5 分", cost: "¥400" },
  ],

  alternateModules: [
    { title: "Day3 市區 ↔ 糸島半日", desc: "櫻井二見浦、Itoshima Beer Lab、海景咖啡。博多→姪濱→轉 bus 約 40 分。" },
    { title: "Day4 由布院 ↔ 北九州+下關", desc: "主線由布院。互換可改小倉・門司・唐戶（Day1 已取消煙火・門司尚未去）。" },
    { title: "Day5 現代福岡 ↔ 熊本", desc: "新幹線 40 分。熊本城、城彩苑。長距離，07:00 出發。" },
    { title: "Day2 拆成兩天", desc: "Day2 太宰府 / Day3 柳川，節奏更悠閒。" },
    { title: "雨天備案", desc: "海之中道水族館、teamLab、九州國立博物館、唐戶すし遊館（室內）。" },
  ],

  days: [
    {
      id: 1,
      date: "8/13（四）",
      title: "抵達 + 博多輕鬆夜",
      image: "assets/fukuoka-trip/d6-hakata.jpg",
      swaps: [
        "市區輕鬆夜（主線）↔ 仍衝門司港半日（無煙火・較趕）",
        "運河城 ↔ 天神散步",
      ],
      places: [
        {
          id: "d1-airport",
          type: "transport",
          name: "福岡機場",
          time: "15:30 抵達",
          lat: 33.5859,
          lng: 130.4506,
          address: "福岡県福岡市博多区大字下臼井778-1",
          image: null,
          mustSee: ["國際線→國內線接駁巴士→地鐵"],
          transport: "地鐵空港線 → 博多（5 分 · ¥260）",
          restaurants: [],
          booking: null,
        },
        {
          id: "d1-hakata-drop",
          type: "hotel",
          name: "博多站（check-in）",
          time: "16:00–16:45",
          lat: 33.5897,
          lng: 130.4207,
          address: "福岡県福岡市博多区博多駅中央街",
          image: "assets/fukuoka-trip/d6-hakata.jpg",
          mustSee: ["飯店 check-in", "稍作休息 · 不趕煙火"],
          transport: "住宿基地 · 全程同一飯店",
          restaurants: [],
          booking: null,
        },
        {
          id: "d1-canal",
          type: "sight",
          name: "博多運河城（輕逛）",
          time: "17:00–19:00",
          lat: 33.5924,
          lng: 130.4087,
          address: "福岡県福岡市博多区住吉1-2",
          image: "assets/food/canal-city.jpg",
          mustSee: ["整點噴泉秀", "どんぐり共和国（龍貓店 · B1）", "拉麵競技場（選）"],
          transport: "博多站步行 10 分 · 或巴士 1 站",
          sources: [
            { platform: "樂吃購", note: "抵達日就近 · 不必衝北九州" },
            { platform: "Google", rating: "4.2", note: "複合商場 · 噴泉免費" },
          ],
          restaurants: [
            { name: "どんぐり共和国（龍貓・吉卜力）", address: "福岡県福岡市博多区住吉1-2-22 キャナルシティオーパ B1F", note: "10:00–21:00 · 巨大トトロ" },
            { name: "博多拉麵競技場", address: "福岡県福岡市博多区住吉1-2 CANAL CITY 5F", note: "8 家拉麵 · 也可晚餐" },
          ],
          booking: null,
        },
        {
          id: "d1-ramen",
          type: "food",
          name: "博多拉麵（首晚）",
          time: "19:00–20:30",
          lat: 33.5905,
          lng: 130.4195,
          address: "福岡県福岡市博多区博多駅前3-23-17",
          image: "assets/food/ramen.jpg",
          mustSee: ["ShinShin 本店（清爽豚骨）", "一風堂 総本店（選）", "運河城拉麵競技場（選）"],
          transport: "博多站步行 5–10 分",
          sources: [
            { platform: "波比看世界", note: "ShinShin 清爽系 · 首晚推薦" },
            { platform: "食べログ", rating: "3.6", note: "博多拉麵人氣店" },
          ],
          restaurants: [
            { name: "博多拉麵 ShinShin 本店", address: "福岡県福岡市博多区博多駅前3-23-17", note: "11:00–23:00 · 清爽豚骨" },
            { name: "一風堂 総本店", address: "福岡県福岡市博多区須崎町1-13-14", note: "白丸元味" },
            { name: "博多一双 デイトス店", address: "福岡県福岡市博多区博多駅中央街1-1", note: "博多站內 · 免走路" },
          ],
          booking: null,
        },
        {
          id: "d1-nakasu-yatai",
          type: "food",
          name: "中洲屋台橫丁",
          time: "20:30–22:00",
          lat: 33.5928,
          lng: 130.4075,
          address: "福岡県福岡市博多区中洲5-3 付近",
          image: "assets/food/yatai.jpg",
          mustSee: ["福岡三大屋台之一", "博多拉麵・串燒・關東煮", "體驗氛圍 · 點少量嚐鮮"],
          transport: "運河城／中洲川端站步行 5 分",
          sources: [
            { platform: "Mimi韓旅遊", note: "觀光化 · 價格偏高 · 點少量嚐鮮" },
            { platform: "Google", rating: "4.0", note: "120+ 家屋台 · 18:00 起" },
          ],
          restaurants: [
            { name: "小金ちゃん", address: "福岡県福岡市博多区中洲5-3 付近", note: "炒拉麵 · 明太子玉子燒" },
            { name: "よしけい", address: "福岡県福岡市博多区中洲", note: "おでん・もつ鍋系屋台" },
          ],
          booking: null,
        },
      ],
    },
    {
      id: 2,
      date: "8/14（五）",
      title: "太宰府 + 柳川",
      image: "assets/fukuoka-trip/d2-dazaifu.jpg",
      swaps: [
        "上午太宰府→下午柳川（推薦）↔ 反向 8:10 柳川船",
        "竈門神社 ↔ 九州國立博物館",
        "鰻魚：本吉屋 ↔ 若松屋 ↔ 六騎",
      ],
      places: [
        {
          id: "d2-dazaifu",
          type: "sight",
          name: "太宰府天滿宮",
          time: "09:00–13:00",
          lat: 33.5215,
          lng: 130.5348,
          address: "福岡県太宰府市宰府4-7-1",
          image: "assets/fukuoka-trip/d2-dazaifu.jpg",
          mustSee: ["表參道", "御本殿", "御神木飛梅", "隈研吾星巴克"],
          transport: "博多→天神（3 分）→西鐵太宰府（45 分）· 套票",
          sources: [
            { platform: "就要玩日本", note: "福岡近郊黃金組合 · 求學業必參拜" },
            { platform: "Google", rating: "4.3", note: "九州第一神社" },
          ],
          restaurants: [
            { name: "やす武", address: "福岡県太宰府市宰府3-2-40", note: "鎌倉老店梅枝餅" },
            { name: "一蘭 太宰府參道店", address: "福岡県太宰府市宰府2-6-24", note: "限定合格五角碗" },
            { name: "Kingberry", address: "福岡県太宰府市宰府2-7-11", note: "甘王草莓大福" },
            { name: "酒殿屋", address: "福岡県太宰府市宰府3-1-30", note: "可兌換套票梅枝餅券" },
          ],
          booking: { status: "should", text: "購買太宰府・柳川觀光套票" },
        },
        {
          id: "d2-starbucks",
          type: "sight",
          name: "隈研吾星巴克（太宰府）",
          time: "09:30 順路",
          lat: 33.5198,
          lng: 130.5355,
          address: "福岡県太宰府市宰府3-2-43",
          image: null,
          mustSee: ["2000 根木條交錯", "表參道起點地標", "限定杯款"],
          transport: "太宰府站步行 3 分 · 表參道入口",
          sources: [
            { platform: "Travel Stay Guide", note: "建築打卡必去" },
            { platform: "Instagram", note: "太宰府 No.1 拍照點" },
          ],
          restaurants: [],
          booking: null,
        },
        {
          id: "d2-yasutake",
          type: "food",
          name: "やす武（梅枝餅）",
          time: "10:00 順路",
          lat: 33.5208,
          lng: 130.5342,
          address: "福岡県太宰府市宰府3-2-40",
          image: null,
          mustSee: ["鎌倉創業老店", "現烤梅枝餅", "表參道必吃"],
          transport: "表參道中段",
          sources: [
            { platform: "食べログ", rating: "3.52", note: "梅枝餅老舗" },
            { platform: "樂吃購", note: "熱騰騰現烤必試" },
          ],
          restaurants: [{ name: "やす武", address: "福岡県太宰府市宰府3-2-40", note: "現烤梅枝餅 · 表參道" }],
          booking: null,
        },
        {
          id: "d2-kyushu-museum",
          type: "sight",
          name: "九州國立博物館",
          time: "12:00 選",
          lat: 33.5208,
          lng: 130.5430,
          address: "福岡県太宰府市石坂4-7-2",
          image: null,
          mustSee: ["黒田長政関連", "浮世繪特展（依檔期）", "雨天備案首選"],
          transport: "太宰府天滿宮旁 · 步行 5 分",
          sources: [{ platform: "樂吃購", note: "竈門神社替代 · 室內" }],
          restaurants: [{ name: "博物館咖啡廳", address: "福岡県太宰府市石坂4-7-2", note: "輕食休息" }],
          booking: null,
        },
        {
          id: "d2-kamado",
          type: "sight",
          name: "寶滿宮竈門神社（選）",
          time: "13:00–13:30",
          lat: 33.5165,
          lng: 130.5230,
          address: "福岡県太宰府市大字内山883",
          image: null,
          mustSee: ["鬼滅之刃巡禮", "天孫降臨傳說"],
          transport: "太宰府站搭巴士約 10 分",
          restaurants: [],
          booking: null,
        },
        {
          id: "d2-yanagawa",
          type: "sight",
          name: "柳川遊船 + 水都",
          time: "15:40–18:00",
          lat: 33.1628,
          lng: 130.4069,
          address: "福岡県柳川市三橋町下古賀（松月乘船場）",
          image: "assets/fukuoka-trip/d2-yanagawa.jpg",
          mustSee: ["川下り 70 分", "沖端運河", "北原白秋故居（選）"],
          transport: "太宰府→柳川（30 分）· 15:40 班次",
          sources: [
            { platform: "樂吃購", note: "水鄉搖船 · 套票含船券" },
            { platform: "Google", rating: "4.2", note: "船夫撐篙 · 白牆垂柳" },
          ],
          restaurants: [
            { name: "元祖 本吉屋 本店", address: "福岡県柳川市旭町69", note: "蒸籠鰻魚飯發源地 · 建議預約", tel: "0944-72-6155" },
            { name: "若松屋", address: "福岡県柳川市沖端町26", note: "百年老店", tel: "0944-72-3163" },
            { name: "民藝茶屋 六騎", address: "福岡県柳川市沖端町68", note: "排隊較少 · 套票有折扣" },
          ],
          booking: { status: "must", text: "🔴 遊船 15:40 必須預約" },
        },
        {
          id: "d2-motoyoshiya",
          type: "food",
          name: "元祖本吉屋（蒸籠鰻魚飯）",
          time: "12:30 午餐",
          lat: 33.1630,
          lng: 130.4055,
          address: "福岡県柳川市旭町69",
          image: null,
          mustSee: ["創業 300 年", "せいろ蒸し ¥4,900", "うなぎ百名店"],
          transport: "西鐵柳川站→旭町本店 · 計程車或步行",
          sources: [
            { platform: "食べログ", rating: "3.73", note: "うなぎ百名店" },
            { platform: "なるほど福岡", note: "柳川必吃 · 錦糸卵せいろ蒸し" },
          ],
          restaurants: [
            { name: "元祖 本吉屋 本店", address: "福岡県柳川市旭町69", note: "10:30–20:00 · 建議預約", tel: "0944-72-6155" },
          ],
          booking: { status: "should", text: "🟡 週末午餐建議電話預約" },
        },
        {
          id: "d2-ohoka",
          type: "sight",
          name: "御花（柳川藩主別邸）",
          time: "14:00 選",
          lat: 33.1635,
          lng: 130.4075,
          address: "福岡県柳川市御花",
          image: null,
          mustSee: ["回遊式庭園", "料亭午餐（選）", "柳川必去文化財"],
          transport: "柳川站周邊 · 遊船前後順路",
          sources: [{ platform: "樂吃購", note: "柳川必去 · 庭園與料亭" }],
          restaurants: [],
          booking: null,
        },
        {
          id: "d2-tetsunabe",
          type: "food",
          name: "博多祇園鉄なべ（晚餐）",
          time: "19:30",
          lat: 33.5935,
          lng: 130.4120,
          address: "福岡県福岡市博多区祇園町2-20",
          image: null,
          mustSee: ["鐵鍋煎餃 B 級美食"],
          transport: "地鐵祇園站 5 號出口步行 3 分",
          sources: [{ platform: "Google", rating: "4.0", note: "B 級グルメ · 鐵鍋餃子" }],
          restaurants: [
            { name: "博多祇園鉄なべ", address: "福岡県福岡市博多区祇園町2-20", note: "17:00–23:00 · 日祝公休", tel: "092-291-0890" },
          ],
          booking: null,
        },
      ],
    },
    {
      id: 3,
      date: "8/15（六）",
      title: "福岡市區經典",
      image: "assets/fukuoka-trip/d3-ohori.jpg",
      swaps: [
        "大濠公園 ↔ 海之中道水族館",
        "櫛田神社 ↔ 東長寺 ↔ 住吉神社",
        "晚餐：もつ鍋 ↔ 水炊き ↔ 屋台",
      ],
      places: [
        {
          id: "d3-ohori",
          type: "sight",
          name: "大濠公園 + 福岡城跡",
          time: "09:00–12:30",
          lat: 33.5862,
          lng: 130.3781,
          address: "福岡県福岡市中央区大濠公園1",
          image: "assets/fukuoka-trip/d3-ohori.jpg",
          mustSee: ["租天鵝船", "舞鶴公園", "日本庭園", "湖景星巴克"],
          transport: "博多→大濠公園站（10 分 · ¥260）",
          sources: [
            { platform: "樂吃購", note: "福岡市區經典公園" },
            { platform: "Google", rating: "4.4", note: "租船 · 福岡城跡" },
          ],
          restaurants: [
            { name: "& LOCALS 大濠公園", address: "福岡県福岡市中央区大濠公園1-9", note: "湖景定食 · 09:00 開 · 週一公休" },
            { name: "ごはんや 飯すけ", address: "福岡県福岡市中央区大名1-14-45", note: "鮮魚定食" },
          ],
          booking: null,
        },
        {
          id: "d3-sumiyoshi",
          type: "sight",
          name: "住吉神社",
          time: "12:45 順路",
          lat: 33.5939,
          lng: 130.4115,
          address: "福岡県福岡市博多区住吉1-41",
          image: null,
          mustSee: ["國家重要文化財本殿", "博多三大神社", "運河城旁 10 分"],
          transport: "大濠→櫛田方向 · 住吉站步行 2 分",
          sources: [{ platform: "日本住宿達人", note: "運河城・櫛田順路" }],
          restaurants: [],
          booking: null,
        },
        {
          id: "d3-kushida",
          type: "sight",
          name: "櫛田神社",
          time: "13:00–14:30",
          lat: 33.5923,
          lng: 130.4100,
          address: "福岡県福岡市博多区上川端町1-41",
          image: "assets/fukuoka-trip/d3-kushida.jpg",
          mustSee: ["博多總鎮守", "縮景千本櫻", "博多傳統工藝御守", "靈泉鶴井水"],
          transport: "地鐵櫛田神社前站步行 1 分",
          sources: [
            { platform: "Ms Wanders", note: "停留 40 分–1 小時 · 早上去避人潮" },
            { platform: "Google", rating: "4.4", note: "祇園山笠 · 免費參拜" },
          ],
          restaurants: [
            { name: "博多一双 祇園店", address: "福岡県福岡市博多区祇園町2-1", note: "卡布奇諾豚骨湯頭" },
            { name: "茶壺烏龍麵 博多あかちょこべ", address: "福岡県福岡市博多区冷泉町9-10", note: "櫛田神社旁" },
          ],
          booking: null,
        },
        {
          id: "d3-kawabata",
          type: "shop",
          name: "川端通商店街",
          time: "14:00 順路",
          lat: 33.5945,
          lng: 130.4085,
          address: "福岡県福岡市博多区上川端町",
          image: null,
          mustSee: ["博多運河沿岸", "山笠花車展示", "善哉廣場"],
          transport: "櫛田神社旁 · 步行即達",
          sources: [{ platform: "Ms Wanders", note: "參拜後逛街吃小吃" }],
          restaurants: [
            { name: "川端善哉", address: "福岡県福岡市博多区上川端町", note: "红豆湯配 mochi" },
          ],
          booking: null,
        },
        {
          id: "d3-canal",
          type: "sight",
          name: "博多運河城 + 中洲",
          time: "15:00–21:00",
          lat: 33.5924,
          lng: 130.4087,
          address: "福岡県福岡市博多区住吉1-2",
          image: null,
          mustSee: ["整點噴泉秀", "中洲川端", "中洲屋台", "拉麵競技場"],
          transport: "櫛田神社步行 10 分",
          sources: [
            { platform: "樂吃購", note: "200+ 店舖 · 噴泉秀" },
            { platform: "Mimi韓旅遊", note: "購物+水舞 · 10 分抵達" },
          ],
          restaurants: [
            { name: "博多拉麵競技場", address: "福岡県福岡市博多区住吉1-2 CANAL CITY 5F", note: "8 家拉麵一次吃" },
            { name: "どんぐり共和国（龍貓・吉卜力）", address: "福岡県福岡市博多区住吉1-2-22 キャナルシティオーパ B1F", note: "10:00–21:00 · 巨大トトロ・フォトスポット" },
            { name: "元祖牛腸鍋 樂天地 本店", address: "福岡県福岡市中央区西中洲6-13", note: "もつ鍋名店 · 建議預約" },
            { name: "博多拉麵 ShinShin 本店", address: "福岡県福岡市博多区博多駅前3-23-17", note: "清爽豚骨" },
            { name: "中洲屋台 小金ちゃん", address: "福岡県福岡市博多区中洲5-3 付近", note: "炒拉麵 · 明太子玉子燒" },
          ],
          booking: { status: "should", text: "🟡 樂天地晚餐建議預約" },
        },
        {
          id: "d3-yatai",
          type: "food",
          name: "中洲屋台橫丁",
          time: "19:00–21:00",
          lat: 33.5928,
          lng: 130.4075,
          address: "福岡県福岡市博多区中洲5-3 付近",
          image: null,
          mustSee: ["福岡屋台文化", "拉麵・串燒・おでん", "那珂川水上巴士（選）"],
          transport: "運河城步行 200m · 中洲川端站",
          sources: [
            { platform: "Mimi韓旅遊", note: "體驗文化 · 價格偏高 · 現金為主" },
            { platform: "Google", rating: "4.0", note: "18:00–01:00 · 越晚越熱鬧" },
          ],
          restaurants: [
            { name: "小金ちゃん", address: "福岡県福岡市博多区中洲5-3 付近", note: "屋台代表" },
            { name: "よしけい", address: "福岡県福岡市博多区中洲", note: "關東煮・內臟鍋" },
          ],
          booking: null,
        },
        {
          id: "d3-hanamidori",
          type: "food",
          name: "博多華味鳥（水炊鍋）",
          time: "18:30 選",
          lat: 33.5908,
          lng: 130.4125,
          address: "福岡県福岡市博多区冷泉町8-1",
          image: null,
          mustSee: ["博多水炊鍋發祥", "雞肉丸・雞皮", "もつ鍋替代"],
          transport: "祇園・中洲區 · 地鐵祇園站",
          sources: [
            { platform: "食べログ", rating: "3.58", note: "水炊き名店" },
            { platform: "波比看世界", note: "濃郁湯頭 · もつ鍋以外選項" },
          ],
          restaurants: [{ name: "博多華味鳥 本店", address: "福岡県福岡市博多区冷泉町8-1", note: "17:00–23:00" }],
          booking: null,
        },
        {
          id: "d3-donki",
          type: "shop",
          name: "唐吉訶德 中洲店",
          time: "20:30 選",
          lat: 33.5938,
          lng: 130.4065,
          address: "福岡県福岡市博多区中洲3-6-11",
          image: null,
          mustSee: ["24 小時", "藥妝・零食", "屋台後補貨"],
          transport: "中洲屋台旁",
          sources: [{ platform: "樂吃購", note: "中洲商圈必逛" }],
          restaurants: [],
          booking: null,
        },
      ],
    },
    {
      id: 4,
      date: "8/16（日）",
      title: "由布院一日遊",
      image: "assets/fukuoka-trip/d2-yanagawa.jpg",
      swaps: [
        "整日 ↔ 北九州 + 下關（小倉・唐戶市場）",
        "金鱗湖晨霧 ↔ 下午到（不必早起）",
        "FLORAL VILLAGE ↔ 由布院美術館",
      ],
      places: [
        {
          id: "d4-yufuin-train",
          type: "transport",
          name: "博多 → 由布院（JR）",
          time: "07:30–10:00",
          lat: 33.5897,
          lng: 130.4207,
          address: "福岡県福岡市博多区博多駅中央街",
          image: null,
          mustSee: ["ゆふいんの森（觀光列車 · 建議指定席）", "ソニック + 久大本線（直達約 2hr）", "週日早班較空"],
          transport: "博多站 JR · ゆふいんの森 07:33／08:00 或 Sonic 07:43 · 約 ¥4,410",
          restaurants: [],
          booking: { status: "should", text: "🟡 由布院之森指定席 · JR 官網或車站" },
        },
        {
          id: "d4-yufuin-station",
          type: "sight",
          name: "由布院站 + 足湯",
          time: "10:00–10:30",
          lat: 33.2583,
          lng: 131.3542,
          address: "大分県由布市湯布院町川上",
          image: "assets/fukuoka-trip/d2-yanagawa.jpg",
          mustSee: ["站前觀光案內", "由布院の森（足湯）", "租腳踏車（選）"],
          transport: "由布院站下車 · 步行進入小鎮",
          sources: [
            { platform: "樂吃購", note: "大分必去溫泉小鎮 · 一日遊經典" },
            { platform: "Google", rating: "4.5", note: "站前即湯之坪起點" },
          ],
          restaurants: [
            { name: "B-speak（ロールケーキ）", address: "大分県由布市湯布院町川上1503-3", note: "排隊名物 · 限購一條 · 10:00 開賣" },
          ],
          booking: null,
        },
        {
          id: "d4-yunotsubo",
          type: "shop",
          name: "湯之坪街道",
          time: "10:30–13:00",
          lat: 33.2620,
          lng: 131.3570,
          address: "大分県由布市湯布院町川上",
          image: "assets/fukuoka-trip/d2-yanagawa.jpg",
          mustSee: ["主街散步", "雜貨・甜點・陶藝", "由布院 樂久登樓（天婦羅蕎麥）", "由布まぶし心（豐後牛）"],
          transport: "由布院站步行 10 分 · 主街約 500m",
          sources: [{ platform: "樂吃購", note: "由布院核心商店街" }],
          restaurants: [
            { name: "由布院 樂久登樓", address: "大分県由布市湯布院町川上1068-1", note: "天婦羅蕎麥 · 午餐人氣" },
            { name: "由布まぶし心", address: "大分県由布市湯布院町川上1503-2", note: "豐後牛蓋飯 · 必吃" },
            { name: "B-speak", address: "大分県由布市湯布院町川上1503-3", note: "瑞士卷 · 伴手禮" },
          ],
          booking: null,
        },
        {
          id: "d4-kinrinko",
          type: "sight",
          name: "金鱗湖",
          time: "13:00–14:00",
          lat: 33.2634,
          lng: 131.3540,
          address: "大分県由布市湯布院町",
          image: "assets/fukuoka-trip/d2-yanagawa.jpg",
          mustSee: ["晨霧名景（07:00 前最佳）", "湖邊散步", "由布岳倒影", "天祖神社"],
          transport: "湯之坪北端步行 5 分",
          sources: [
            { platform: "Google", rating: "4.4", note: "由布院象徵景點" },
            { platform: "Mimi韓旅遊", note: "溫泉與湖水交匯 · 拍照聖地" },
          ],
          restaurants: [],
          booking: null,
        },
        {
          id: "d4-floral-village",
          type: "sight",
          name: "由布院 FLORAL VILLAGE（龍貓之屋）",
          time: "14:00–15:30",
          lat: 33.2655,
          lng: 131.3520,
          address: "大分県由布市湯布院町川上1503-3",
          image: "assets/fukuoka-trip/d2-yanagawa.jpg",
          mustSee: ["トトロの家（龍貓之屋 · 吉卜力授權）", "彼得兔・爱丽丝童话村", "彩色小鎮拍照", "どんぐり共和国"],
          transport: "金鱗湖步行 5 分 · 湯之坪西端",
          sources: [{ platform: "樂吃購", note: "由布院必拍 · 童話風格園區" }],
          restaurants: [],
          booking: null,
        },
        {
          id: "d4-yufuin-cafe",
          type: "food",
          name: "由布院甜點・咖啡（選）",
          time: "15:30–16:30",
          lat: 33.2615,
          lng: 131.3565,
          address: "大分県由布市湯布院町",
          image: null,
          mustSee: ["Pâtisserie Roket Cake", "由布院 花麥（選）", "茶屋 暫（選）"],
          transport: "湯之坪沿線",
          sources: [{ platform: "Google", rating: "4.3", note: "甜點店林立" }],
          restaurants: [
            { name: "Pâtisserie Roket Cake", address: "大分県由布市湯布院町川上1592-1", note: "布丁・蛋糕" },
            { name: "B-speak", address: "大分県由布市湯布院町川上1503-3", note: "若早上售完可下午再試" },
          ],
          booking: null,
        },
        {
          id: "d4-yufuin-return",
          type: "transport",
          name: "由布院 → 博多（返程）",
          time: "17:00–19:30",
          lat: 33.2583,
          lng: 131.3542,
          address: "大分県由布市湯布院町川上",
          image: null,
          mustSee: ["17:00–18:00 班次較多", "ゆふいんの森 16:10／17:10", "回博多晚餐或屋台"],
          transport: "由布院站 → 博多 · 約 2hr",
          restaurants: [],
          booking: null,
        },
      ],
    },
    {
      id: 5,
      date: "8/17（一）",
      title: "現代福岡 + 購物",
      image: "assets/fukuoka-trip/d5-tower.jpg",
      swaps: [
        "teamLab ↔ 三麗鷗夢幻公園",
        "福岡塔 ↔ 皿倉山夜景",
      ],
      places: [
        {
          id: "d5-teamlab",
          type: "sight",
          name: "LaLaport + teamLab Forest",
          time: "09:30–13:00",
          lat: 33.5953,
          lng: 130.3623,
          address: "福岡県福岡市中央区地行浜2-2-6 BOSS E・ZO FUKUOKA 5F",
          image: "assets/fukuoka-trip/d5-tower.jpg",
          mustSee: ["1:1 ν 鋼彈立像", "teamLab 捕捉並收集的森林", "V-World（選）"],
          transport: "博多→百道浜 巴士 25 分",
          sources: [
            { platform: "Travel Stay Guide", note: "鋼彈迷 · 親子 · 室內血拼" },
            { platform: "Google", rating: "4.3", note: "teamLab 熱門時段售罄" },
          ],
          restaurants: [
            { name: "Pain Stock", address: "福岡県福岡市中央区大名1-12-11", note: "明太子麵包 · 天神店人少" },
            { name: "BOSS E・ZO 內餐廳", address: "福岡県福岡市中央区地行浜2-2-6", note: "一風堂等" },
          ],
          booking: { status: "must", text: "🔴 teamLab 必須預約時段" },
        },
        {
          id: "d5-gundam",
          type: "event",
          name: "ν 鋼彈立像（百道浜）",
          time: "10:00 順路",
          lat: 33.5960,
          lng: 130.3630,
          address: "福岡県福岡市中央区地行浜2-2-6",
          image: null,
          mustSee: ["1:1 实物大 νガンダム", "整點動作演示", "LaLaport 前廣場"],
          transport: "LaLaport 正門",
          sources: [{ platform: "官方", note: "LaLaport 福岡地標" }],
          restaurants: [],
          booking: null,
        },
        {
          id: "d5-tower",
          type: "sight",
          name: "福岡塔",
          time: "16:30–18:00",
          lat: 33.5931,
          lng: 130.3516,
          address: "福岡県福岡市早良区百道浜2-3-26",
          image: "assets/fukuoka-trip/d5-tower.jpg",
          mustSee: ["234m 日本最高海濱塔", "360° 展望", "百道海濱公園"],
          transport: "E・ZO→福岡塔 巴士 10 分",
          sources: [{ platform: "日本住宿達人", note: "福岡地標 · 海濱夜景" }],
          restaurants: [],
          booking: null,
        },
        {
          id: "d5-sasakiyama",
          type: "sight",
          name: "皿倉山夜景（選）",
          time: "19:00 選",
          lat: 33.8467,
          lng: 130.7956,
          address: "福岡県北九州市八幡西区皿倉山",
          image: null,
          mustSee: ["日本新三大夜景", "纜車登頂", "福岡塔替代"],
          transport: "博多→香椎→纜車 · 約 1hr",
          sources: [{ platform: "樂吃購", note: "百億美元夜景 · 需半日" }],
          restaurants: [],
          booking: null,
        },
        {
          id: "d5-tenjin",
          type: "shop",
          name: "天神採買",
          time: "18:30–21:00",
          lat: 33.5904,
          lng: 130.4017,
          address: "福岡県福岡市中央区天神",
          image: null,
          mustSee: ["天神地下街", "PARCO", "大國藥妝", "明太子伴手禮"],
          transport: "福岡塔→天神 地鐵 15 分 · 天神→博多 3 分",
          sources: [
            { platform: "樂吃購", note: "福岡最大購物區" },
            { platform: "波比看世界", note: "明太子・藥妝・甜點" },
          ],
          restaurants: [
            { name: "元祖博多明太重", address: "福岡県福岡市中央区大名1-11-14", note: "明太子定食 · 常排隊" },
            { name: "BAKE 起司塔", address: "福岡県福岡市中央区天神2-5-35 天神地下街", note: "甜點伴手禮" },
            { name: "葫蘆壽司", address: "福岡県福岡市中央区今泉1-15-20", note: "天神排隊 · 青花魚海膽" },
          ],
          booking: null,
        },
        {
          id: "d5-tenjin-chika",
          type: "shop",
          name: "天神地下街",
          time: "19:00 順路",
          lat: 33.5904,
          lng: 130.4017,
          address: "福岡県福岡市中央区天神2",
          image: null,
          mustSee: ["590 店舖", "BAKE・明太子", "雨天購物"],
          transport: "天神站直結",
          sources: [{ platform: "樂吃購", note: "九州最大地下街" }],
          restaurants: [{ name: "BAKE", address: "天神地下街", note: "起司塔伴手禮" }],
          booking: null,
        },
        {
          id: "d5-parco",
          type: "shop",
          name: "福岡 PARCO",
          time: "19:30 順路",
          lat: 33.5901,
          lng: 130.3989,
          address: "福岡県福岡市中央区天神2-11-1",
          image: null,
          mustSee: ["潮流服飾", "Loft・無印", "天神核心"],
          transport: "天神地下街步行",
          sources: [{ platform: "Google", rating: "4.1", note: "年輕人購物" }],
          restaurants: [],
          booking: null,
        },
        {
          id: "d5-meizhongzi",
          type: "food",
          name: "元祖博多明太重",
          time: "20:00 晚餐",
          lat: 33.5895,
          lng: 130.3995,
          address: "福岡県福岡市中央区大名1-11-14",
          image: null,
          mustSee: ["明太子定食", "整條明太子飯", "天神排隊名店"],
          transport: "天神大名",
          sources: [
            { platform: "食べログ", rating: "3.48", note: "明太子專門" },
            { platform: "波比看世界", note: "福岡必吃明太子" },
          ],
          restaurants: [{ name: "元祖博多明太重", address: "福岡県福岡市中央区大名1-11-14", note: "11:00–22:00" }],
          booking: null,
        },
      ],
    },
    {
      id: 6,
      date: "8/18（二）",
      title: "返港日",
      image: "assets/fukuoka-trip/d6-hakata.jpg",
      swaps: ["加櫛田神社（若 Day3 未去）", "拉麵：ShinShin ↔ 一蘭 ↔ 一雙"],
      places: [
        {
          id: "d6-shopping",
          type: "shop",
          name: "博多站伴手禮",
          time: "09:00–12:00",
          lat: 33.5897,
          lng: 130.4207,
          address: "福岡県福岡市博多区博多駅中央街1-1 JR博多シティ",
          image: "assets/fukuoka-trip/d6-hakata.jpg",
          mustSee: ["博多阪急 みやげ市", "AMU PLAZA", "筑紫通和菓子"],
          transport: "住宿即博多站",
          sources: [
            { platform: "樂吃購", note: "博多駅一番街 · 伴手禮集中" },
            { platform: "波比看世界", note: "明太子・菓子・可頌" },
          ],
          restaurants: [
            { name: "博多拉麵 ShinShin", address: "福岡県福岡市博多区博多駅前3-23-17", note: "最後一碗拉麵" },
            { name: "一蘭 博多総本社", address: "福岡県福岡市博多区総泉寺町5-3-2", note: "總本店" },
            { name: "博多一双 デイトス店", address: "福岡県福岡市博多区博多駅中央街1-1", note: "車站內方便" },
          ],
          booking: null,
        },
        {
          id: "d6-ilforno",
          type: "food",
          name: "il FORNO del Mignon（可頌）",
          time: "09:30 早餐",
          lat: 33.5895,
          lng: 130.4209,
          address: "福岡県福岡市博多区博多駅中央街1-1 JR博多シティ",
          image: null,
          mustSee: ["博多站排隊可頌", "明太子可頌", "伴手禮人氣"],
          transport: "博多駅 1F",
          sources: [
            { platform: "食べログ", rating: "3.72", note: "パン百名店" },
            { platform: "波比看世界", note: "車站必買甜點" },
          ],
          restaurants: [{ name: "il FORNO del Mignon", address: "JR博多シティ 1F", note: "07:00 起 · 售完為止" }],
          booking: null,
        },
        {
          id: "d6-ippudo",
          type: "food",
          name: "一風堂 総本店（選）",
          time: "11:00 選",
          lat: 33.5903,
          lng: 130.4186,
          address: "福岡県福岡市博多区須崎町1-13-14",
          image: null,
          mustSee: ["博多拉麵發祥地之一", "白丸元味", "返港前最後一餐"],
          transport: "博多站步行 8 分",
          sources: [{ platform: "Google", rating: "4.0", note: "全球連鎖總店" }],
          restaurants: [{ name: "一風堂 総本店", address: "福岡県福岡市博多区須崎町1-13-14", note: "11:00–23:00" }],
          booking: null,
        },
        {
          id: "d6-airport",
          type: "transport",
          name: "福岡機場（返港）",
          time: "14:30 出發 · CX529 17:40",
          lat: 33.5859,
          lng: 130.4506,
          address: "福岡県福岡市博多区大字下臼井778-1",
          image: null,
          mustSee: ["15:00 前抵達 check-in", "國內線→國際線接駁巴士"],
          transport: "博多→福岡機場 地鐵 5 分 · ¥260",
          restaurants: [],
          booking: { status: "done", text: "CX529 · HKG 20:25 抵達" },
        },
      ],
    },
  ],
};

const TYPE_LABELS = {
  sight: "景點",
  food: "美食",
  event: "活動",
  shop: "購物",
  hotel: "住宿",
  transport: "交通",
  swap: "互換",
  recommend: "推薦",
  poi: "值得去",
};

const TYPE_COLORS = {
  sight: "#2563eb",
  food: "#ea580c",
  event: "#dc2626",
  shop: "#7c3aed",
  hotel: "#059669",
  transport: "#64748b",
  swap: "#0891b2",
  recommend: "#f59e0b",
  poi: "#6366f1",
};

const BOOKING_LABELS = {
  done: "已完成",
  must: "必須預約",
  should: "建議預約",
  skip: "已取消／不去",
};
